const { getCountry, getCurrency, COUNTRY_CONFIG } = require('../config');
const { genText } = require('../gemini');
const { sendMessage } = require('../send');

async function showSalesForecast(phone, userRef) {
    const userData = (await userRef.get()).data();
    const lang = userData.language || 'bm';
    const cc = getCountry(userData);
    const cur = cc.currency;
    const sales = userData.sales || [];
    const expenses = userData.expenses || [];
    const totalSales = sales.reduce((s, x) => s + (x.amount || 0), 0);
    const totalExpenses = expenses.reduce((s, x) => s + (x.amount || 0), 0);
    const count = sales.length;

    if (count < 3) {
        await sendMessage(phone, lang === 'bm'
            ? '⚠️ *Perlukan sekurang-kurangnya 3 rekod jualan* untuk ramalan AI.\n\nRekod lebih banyak jualan dahulu, kemudian cuba lagi!\nTaip *MENU* untuk kembali'
            : '⚠️ *Need at least 3 sales records* for AI forecast.\n\nRecord more sales first, then try again!\nType *MENU* to go back'
        );
        return;
    }

    await sendMessage(phone, lang === 'bm' ? '📈 Sedang menganalisis corak jualan awak...' : '📈 Analyzing your sales patterns...');

    const salesTimeline = sales.slice(-15).map(s => `- ${s.date || '?'}: ${cur}${s.amount || 0} (${s.item || '?'})`).join('\n');
    const expenseTimeline = expenses.slice(-10).map(e => `- ${e.date || '?'}: ${cur}${e.amount || 0} (${e.item || '?'})`).join('\n');
    const langInstr = lang === 'bm' ? 'Bahasa Malaysia yang mudah' : 'simple English';

    const prompt = `You are a predictive analytics AI for small ASEAN businesses.
Respond in ${langInstr}.

BUSINESS INFO:
- Business: ${userData.business_name || '?'}
- Product: ${userData.product || '?'}
- Country: ${cc.name}
- State: ${userData.user_state || '?'}
- Monthly Revenue (stated): ${userData.monthly_revenue || '?'}
- Total Recorded Sales: ${cur}${totalSales}
- Total Expenses: ${cur}${totalExpenses}
- Number of transactions: ${count}

RECENT SALES (latest first):
${salesTimeline}

RECENT EXPENSES:
${expenseTimeline}

Provide EXACTLY this format:
📈 *RAMALAN JUALAN / SALES FORECAST*

🔮 *Ramalan 30 Hari Seterusnya:*
• Anggaran jualan: ${cur}[amount range]
• Trend: [naik/turun/stabil] [reason]

📊 *Corak Yang Dikesan:*
• [pattern 1]
• [pattern 2]
• [pattern 3]

💡 *Cadangan Untuk Tingkatkan Jualan:*
• [specific actionable tip 1]
• [specific actionable tip 2]
• [specific actionable tip 3]

⚠️ *Risiko:*
• [1 risk based on the data]

Keep it practical and data-driven. Reference their actual numbers.`;

    let response = '';
    try { response = await genText(prompt); } catch { response = lang === 'bm' ? 'Maaf, cuba lagi.' : 'Sorry, try again.'; }

    await sendMessage(phone, lang === 'bm'
        ? `📈 *RAMALAN JUALAN AI*\n_${userData.business_name || ''} — ${cc.flag} ${userData.user_state || cc.name}_\n\n${response}\n\n━━━━━━━━━━━━━━━━━━━━\n🔬 _Ramalan dijana oleh AI berdasarkan data jualan sebenar awak_\n━━━━━━━━━━━━━━━━━━━━\n\nTaip *MENU* untuk kembali`
        : `📈 *AI SALES FORECAST*\n_${userData.business_name || ''} — ${cc.flag} ${userData.user_state || cc.name}_\n\n${response}\n\n━━━━━━━━━━━━━━━━━━━━\n🔬 _Forecast generated by AI based on your actual sales data_\n━━━━━━━━━━━━━━━━━━━━\n\nType *MENU* to go back`
    );
}

async function showSupplyChainTips(phone, userRef) {
    const userData = (await userRef.get()).data();
    const lang = userData.language || 'bm';
    const cc = getCountry(userData);
    const cur = cc.currency;
    const sales = userData.sales || [];
    const expenses = userData.expenses || [];
    const totalSales = sales.reduce((s, x) => s + (x.amount || 0), 0);
    const totalExpenses = expenses.reduce((s, x) => s + (x.amount || 0), 0);
    const profitMargin = totalSales > 0 ? Math.round(((totalSales - totalExpenses) / totalSales) * 100) : 0;

    await sendMessage(phone, lang === 'bm' ? '📦 Sedang menganalisis rantaian bekalan awak...' : '📦 Analyzing your supply chain...');

    const expenseList = expenses.slice(-15).map(e => `- ${e.date || '?'}: ${cur}${e.amount || 0} (${e.item || '?'})`).join('\n') || 'No expenses recorded yet';
    const salesItems = sales.slice(-10).map(s => `- ${s.item || '?'}: ${cur}${s.amount || 0}`).join('\n');
    const langInstr = lang === 'bm' ? 'Bahasa Malaysia yang mudah' : 'simple English';

    const prompt = `You are an AI supply chain advisor for small ASEAN businesses.
Respond in ${langInstr}.

BUSINESS INFO:
- Business: ${userData.business_name || '?'}
- Product: ${userData.product || '?'}
- Country: ${cc.name}, State: ${userData.user_state || '?'}
- Total Sales: ${cur}${totalSales}
- Total Expenses: ${cur}${totalExpenses}
- Profit Margin: ${profitMargin}%

EXPENSE RECORDS:
${expenseList}

WHAT THEY SELL:
${salesItems}

Provide EXACTLY this format:

📦 *ANALISIS RANTAIAN BEKALAN*

💰 *Kesihatan Kos:*
• Margin keuntungan: ${profitMargin}% — [assessment]
• Nisbah kos bahan: [analysis]

🏭 *Cadangan Pembekal & Inventori:*
• [Tip 1 specific to their product]
• [Tip 2 inventory management]
• [Tip 3 seasonal stocking]

📉 *Cara Kurangkan Kos:*
• [Cost saving tip 1]
• [Cost saving tip 2]

🤝 *Peluang Kerjasama:*
• [Partner/cooperative suggestion]
• [Platform/marketplace suggestion for their country]`;

    let response = '';
    try { response = await genText(prompt); } catch { response = lang === 'bm' ? 'Maaf, cuba lagi.' : 'Sorry, try again.'; }

    await sendMessage(phone, lang === 'bm'
        ? `📦 *TIP RANTAIAN BEKALAN AI*\n_${userData.business_name || ''} — ${cc.flag} ${userData.user_state || cc.name}_\n\n${response}\n\n━━━━━━━━━━━━━━━━━━━━\n🔬 _Analisis dijana oleh AI berdasarkan data perbelanjaan sebenar awak_\n━━━━━━━━━━━━━━━━━━━━\n\n💡 Rekod perbelanjaan awak untuk analisis lebih tepat!\nTaip *MENU* untuk kembali`
        : `📦 *AI SUPPLY CHAIN TIPS*\n_${userData.business_name || ''} — ${cc.flag} ${userData.user_state || cc.name}_\n\n${response}\n\n━━━━━━━━━━━━━━━━━━━━\n🔬 _Analysis generated by AI based on your actual expense data_\n━━━━━━━━━━━━━━━━━━━━\n\n💡 Record your expenses for more accurate analysis!\nType *MENU* to go back`
    );
}

async function showExportGuide(phone, userRef) {
    const userData = (await userRef.get()).data();
    const lang = userData.language || 'bm';
    const cc = getCountry(userData);
    const cur = cc.currency;
    const sales = userData.sales || [];
    const totalSales = sales.reduce((s, x) => s + (x.amount || 0), 0);

    await sendMessage(phone, lang === 'bm' ? '🌏 Sedang menganalisis peluang eksport ASEAN...' : '🌏 Analyzing ASEAN export opportunities...');

    const otherCountries = Object.entries(COUNTRY_CONFIG)
        .filter(([k]) => k !== (userData.country || 'MY'))
        .map(([, v]) => `${v.flag} ${v.name}`).join(', ');
    const langInstr = lang === 'bm' ? 'Bahasa Malaysia yang mudah' : 'simple English';

    const prompt = `You are an ASEAN cross-border trade advisor for small businesses.
Respond in ${langInstr}.

BUSINESS INFO:
- Business: ${userData.business_name || '?'}
- Product: ${userData.product || '?'}
- Home Country: ${cc.name} (${cc.flag})
- State: ${userData.user_state || '?'}
- Monthly Revenue: ${userData.monthly_revenue || '?'}
- Total Recorded Sales: ${cur}${totalSales}
- Credit Score: ${userData.credit_score || 'N/A'}/100

TARGET MARKETS: ${otherCountries}

Provide EXACTLY this format:

🌏 *PANDUAN EKSPORT ASEAN*

📊 *Penilaian Kesediaan Eksport:*
• Kesediaan: [Sedia / Hampir sedia / Perlu persediaan] — [1 sentence why]

🎯 *Pasaran Sasaran Terbaik:*
• [Country 1] — [why their product fits]
• [Country 2] — [why]

📋 *Langkah Untuk Mula Eksport:*
1. [Step 1]
2. [Step 2]
3. [Step 3]
4. [Step 4]

💰 *Anggaran Kos Eksport:*
• [Typical costs for small MSME]

🛒 *Platform E-Commerce Serantau:*
• [2-3 actual ASEAN marketplace platforms]

⚖️ *Peraturan Penting:*
• [1-2 key regulations]

Keep it specific to their product (${userData.product || '?'}) and home country (${cc.name}).
Focus on practical, low-cost entry strategies. Mention ASEAN Free Trade Area (AFTA) benefits where relevant.`;

    let response = '';
    try { response = await genText(prompt); } catch { response = lang === 'bm' ? 'Maaf, cuba lagi.' : 'Sorry, try again.'; }

    await sendMessage(phone, lang === 'bm'
        ? `🌏 *PANDUAN EKSPORT ASEAN*\n_${userData.business_name || ''} — ${cc.flag} ${userData.user_state || cc.name}_\n\n${response}\n\n━━━━━━━━━━━━━━━━━━━━\n🔬 _Panduan dijana oleh AI berdasarkan profil perniagaan awak_\n🌐 _Memanfaatkan rangka kerja ASEAN Free Trade Area (AFTA)_\n━━━━━━━━━━━━━━━━━━━━\n\nTaip *MENU* untuk kembali`
        : `🌏 *ASEAN EXPORT GUIDE*\n_${userData.business_name || ''} — ${cc.flag} ${userData.user_state || cc.name}_\n\n${response}\n\n━━━━━━━━━━━━━━━━━━━━\n🔬 _Guide generated by AI based on your business profile_\n🌐 _Leveraging ASEAN Free Trade Area (AFTA) framework_\n━━━━━━━━━━━━━━━━━━━━\n\nType *MENU* to go back`
    );
}

module.exports = { showSalesForecast, showSupplyChainTips, showExportGuide };
